import unittest

import apiritif
from apiritif.feeders import CSVFeeder

feeder = CSVFeeder([
    {"path": "data1.csv"}, 
    {"path": "dir/data2.csv", "variable-names": "addon,plugin"}])


def setup():
    feeder.read_vars()


class TestSimple(unittest.TestCase):    # generated by taurus
    def setUp(self):
        self.vars = feeder.get_vars()

    def test_1_httpblazedemocomnamepass(self):
        with apiritif.transaction('http://blazedemo.com/{}/{}'.format(self.vars['name'], self.vars['pass'])):
            response = apiritif.http.get('http://blazedemo.com/{}/{}'.format(self.vars['name'], self.vars['pass']))

    def test_2_httpblazedemocomaddon(self):
        with apiritif.transaction('http://blazedemo.com/{}'.format(self.vars['addon'])):
            response = apiritif.http.get('http://blazedemo.com/{}'.format(self.vars['addon']))


class TestFromUser(unittest.TestCase):  # added by user after generation
    def test_something(self):
        print(feeder.get_vars())
